name: Release
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  release:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 16
          branches: main
          extra_plugins: |
            @semantic-release/changelog@6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
